config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :posts
  get "pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :title, :content ])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= content_for(:title) || "App1" %></title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="mobile-web-app-capable" content="yes">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= yield :head %>
		<%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
		<%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
		<link rel="icon" href="/icon.png" type="image/png">
		<link rel="icon" href="/icon.svg" type="image/svg+xml">
		<link rel="apple-touch-icon" href="/icon.png">
		<%# Includes all stylesheet files in app/assets/stylesheets %>
		<%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
		<%= javascript_importmap_tags %>
		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
	</head>
	<body>
		<div class="container py-3">
			<%= render 'shared/nav' %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/pages/home.html.erb
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
	<h1 class="display-4 fw-normal text-body-emphasis">Pricing</h1>
	<p class="fs-5 text-body-secondary">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
</div>
<main>
	<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
		<div class="col">
			<div class="card mb-4 rounded-3 shadow-sm">
				<div class="card-header py-3">
					<h4 class="my-0 fw-normal">Free</h4>
				</div>
				<div class="card-body">
					<h1 class="card-title pricing-card-title">$0<small class="text-body-secondary fw-light">/mo</small></h1>
					<ul class="list-unstyled mt-3 mb-4">
						<li>10 users included</li>
						<li>2 GB of storage</li>
						<li>Email support</li>
						<li>Help center access</li>
					</ul>
					<button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button>
				</div>
			</div>
		</div>
		<div class="col">
			<div class="card mb-4 rounded-3 shadow-sm">
				<div class="card-header py-3">
					<h4 class="my-0 fw-normal">Pro</h4>
				</div>
				<div class="card-body">
					<h1 class="card-title pricing-card-title">$15<small class="text-body-secondary fw-light">/mo</small></h1>
					<ul class="list-unstyled mt-3 mb-4">
						<li>20 users included</li>
						<li>10 GB of storage</li>
						<li>Priority email support</li>
						<li>Help center access</li>
					</ul>
					<button type="button" class="w-100 btn btn-lg btn-primary">Get started</button>
				</div>
			</div>
		</div>
		<div class="col">
			<div class="card mb-4 rounded-3 shadow-sm border-primary">
				<div class="card-header py-3 text-bg-primary border-primary">
					<h4 class="my-0 fw-normal">Enterprise</h4>
				</div>
				<div class="card-body">
					<h1 class="card-title pricing-card-title">$29<small class="text-body-secondary fw-light">/mo</small></h1>
					<ul class="list-unstyled mt-3 mb-4">
						<li>30 users included</li>
						<li>15 GB of storage</li>
						<li>Phone and email support</li>
						<li>Help center access</li>
					</ul>
					<button type="button" class="w-100 btn btn-lg btn-primary">Contact us</button>
				</div>
			</div>
		</div>
	</div>
	<h2 class="display-6 text-center mb-4">Compare plans</h2>
	<div class="table-responsive">
		<table class="table text-center">
			<thead>
				<tr>
					<th style="width: 34%;"></th>
					<th style="width: 22%;">Free</th>
					<th style="width: 22%;">Pro</th>
					<th style="width: 22%;">Enterprise</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th scope="row" class="text-start">Public</th>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
				</tr>
				<tr>
					<th scope="row" class="text-start">Private</th>
					<td></td>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
				</tr>
			</tbody>
			<tbody>
				<tr>
					<th scope="row" class="text-start">Permissions</th>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
				</tr>
				<tr>
					<th scope="row" class="text-start">Sharing</th>
					<td></td>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
				</tr>
				<tr>
					<th scope="row" class="text-start">Unlimited members</th>
					<td></td>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
				</tr>
				<tr>
					<th scope="row" class="text-start">Extra security</th>
					<td></td>
					<td></td>
					<td><svg class="bi" width="24" height="24"><use xlink:href="#check"></use></svg></td>
				</tr>
			</tbody>
		</table>
	</div>
</main>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
	<div class="row">
		<div class="col-12 col-md">
			<img class="mb-2" src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="" width="24" height="19">
			<small class="d-block mb-3 text-body-secondary">© 2017–2024</small>
		</div>
		<div class="col-6 col-md">
			<h5>Features</h5>
			<ul class="list-unstyled text-small">
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a></li>
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
			</ul>
		</div>
		<div class="col-6 col-md">
			<h5>Resources</h5>
			<ul class="list-unstyled text-small">
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
			</ul>
		</div>
		<div class="col-6 col-md">
			<h5>About</h5>
			<ul class="list-unstyled text-small">
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
				<li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
			</ul>
		</div>
	</div>
</footer>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.textarea :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/shared/_nav.html.erb
<header>
	<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
		<a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
			<svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
			<span class="fs-4">App Logo</span>
		</a>
		<nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
			<a class="me-3 py-2 link-body-emphasis text-decoration-none" href="/">home</a>
			<a class="me-3 py-2 link-body-emphasis text-decoration-none" href="/posts">Posts</a>
			<a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Support</a>
			<a class="py-2 link-body-emphasis text-decoration-none" href="#">Pricing</a>
			<% if authenticated? %>
				<%= button_to "Sign Out", session_path, class: "btn btn-danger btn-sm", method: :delete  %>
			<% else %>
				<%= link_to "Sign In", new_session_path, class: "btn btn-primary btn-sm" %>
			<% end %>
		</nav>
	</div>
</header>